Haehnchen/idea-php-symfony2-plugin

src/fr/adrienbrault/idea/symfony2plugin/util/dict/ServiceUtil.java

FormTypeExtensions must implement `\Symfony\Component\Form\FormTypeExtensionInterface` not `\Symfony\Component\Form\FormExtensionInterface`. Symfony's abstract class `AbstractTypeExtension` does this aswell.
See http://symfony.com/doc/current/reference/dic_tags.html#form-type-extension
and http://symfony.com/doc/current/cookbook/form/create_form_type_extension.html

[Form] Fixed wrong Inspection for FormTypeExtensions

---

src/resources/fileTemplates/controller.php

When generating a new Controller (right clicking a folder), the classname had a double Controller word in it. eg. TestControllerController.
This removes one of them.

[Fix] Remove double Controller in classname

---

src/resources/symfony2-config.xml

according to http://symfony.com/blog/new-in-symfony-2-6-improvements-for-the-translation-component#missing-translations-logging

add translator.logging parameter

---

src/resources/fileTemplates/container.yml

1.: according the symfony best practices, parameters for class names should be avoided: http://symfony.com/doc/current/best_practices/business-logic.html#service-no-class-parameter
2.: service and parameter expressions in yaml must be quoted: http://symfony.com/doc/current/best_practices/business-logic.html#service-no-class-parameter

fix container config

---

src/fr/adrienbrault/idea/symfony2plugin/stubs/indexes/AnnotationRoutesStubIndex.java
src/fr/adrienbrault/idea/symfony2plugin/util/AnnotationBackportUtil.java

PhpUse#getOriginal is deprecated since PhpStorm 2016.1. This method was always returning almost the same value as #getFQN so this change most probably will not break anything. Unfortunately I've no chance to check it so it would be great if you'll perform some tests before or just after the merge. This pull request is rather notification than complete fix.

PhpUse#getOriginal is deprecated, use #getFQN instead

---

src/fr/adrienbrault/idea/symfony2plugin/intentions/yaml/YamlUnquotedColon.java
tests/fr/adrienbrault/idea/symfony2plugin/tests/intentions/yaml/YamlUnquotedColonTest.java

Colons in mapping values are fine as long as they are not followed by a
space character.

don't report standalone colon in mapping value

---

src/fr/adrienbrault/idea/symfony2plugin/util/IdeHelper.java

Hello,
This PR to fix the test done on the cache folder for version 3.0. See #810 
The test indicates that if the var/cache folder does not exist (4274c9c), it becomes the default configuration.
The behavior must be reversed.
Regards

[#810] Fixes the folder test for the cache

---

src/fr/adrienbrault/idea/symfony2plugin/Settings.java

Reflect changes, introduced in https://github.com/symfony/symfony/pull/20147
@stof Do you know any other paths that should be updated?
@Haehnchen imho it's time to remove deprecated option for url generator path.

Adopt default routing files path to Symfony > 2.7.20

---

CHANGELOG.md

Double underscore outside a code span is the Markdown markup for bold, which breaks the message

fix markup in the changelog

---

META-INF/plugin.xml
src/fr/adrienbrault/idea/symfony2plugin/Symfony2ProjectComponent.java
src/fr/adrienbrault/idea/symfony2plugin/TwigHelper.java
src/fr/adrienbrault/idea/symfony2plugin/config/utils/ConfigUtil.java
src/fr/adrienbrault/idea/symfony2plugin/templating/path/BundleOverwriteNamespaceExtensions.java
src/fr/adrienbrault/idea/symfony2plugin/templating/path/GlobalAppTwigNamespaceExtension.java
src/fr/adrienbrault/idea/symfony2plugin/util/FilesystemUtil.java
src/fr/adrienbrault/idea/symfony2plugin/util/yaml/YamlPsiElementFactory.java
tests/fr/adrienbrault/idea/symfony2plugin/tests/TwigHelperTempTest.java
tests/fr/adrienbrault/idea/symfony2plugin/tests/config/utils/ConfigUtilTempTest.java
tests/fr/adrienbrault/idea/symfony2plugin/tests/templating/path/GlobalAppTwigNamespaceExtensionTest.java

provide add better "app" folder detection and add more tests for related features #1036

---

src/fr/adrienbrault/idea/symfony2plugin/routing/RouteHelper.java

Let me know if this is really the right place. Do we need to check the projects' Symfony version? (If so: is there a tool already?)
Closes: #1071

Add _fragment route parameter as always available

---

src/inspectionDescriptions/TwigAssetsTagMissingInspection.html

Asset function is not related to Assetic. Instead, it's related to Symfony Twig extension.
This PR makes the link pointing to correct documentation page

Fix link to asset function

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/action/quickfix/CorrectClassNameCasingYamlLocalQuickFix.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/codeInspection/service/ServiceDeprecatedClassesInspection.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/inspection/YamlClassInspection.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/dic/inspection/YamlClassInspectionTest.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/twig/annotation/TemplateAnnotationAnnotatorTest.java

Since PhpIndex searches by fqn are not case sensitive,
the missing class name inspection might not trigger.
Contains a quick fix that can correct the FQN.
Closes: #1200

Add inspection and quick fix for fuzzy service class names in YAML

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/config/yaml/YamlGoToDeclarationHandler.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/config/yaml/YamlGoToDeclarationHandlerTest.java

Add YAML const GoTo Target for Symfony 3.2+ style constants

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/intention/PhpServiceArgumentIntention.java

Move write action out of AWT event for PhpServiceArgumentIntention

---

CHANGELOG.md
MAINTENANCE.md
build.gradle
prepare-release.sh
src/main/resources/META-INF/change-notes.html

This changeset includes a few additions to the build chain, a word about releasing the plugin for maintainers, a script to generate the changelog between `HEAD` and the last release - and the changelog.
Once merged, I'll release a new version of the plugin to the repository.
Sorry this took so long to get to.

Prepare first gradle-based release (0.16.166)

---

.travis.yml
build.gradle

Also:
* add verifyPlugin task to travis build to avoid invalid plugin.xml

Do not set until constraint so EAP users can still use the plugin

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/translation/dict/TranslationUtil.java

For the upcoming Symfony 4.2 release, the `Symfony\Component\Translation\TranslatorInterface` became deprecated in favor of `Symfony\Contracts\Translation\TranslatorInterface`.
For the translation key detection to work again when injecting the new Translator, I added the new namespace.
For backwards compatibility for older Symfony versions, the "old" namespace stays in.

Symfony 4.2: Translation detection fixed for new TranslatorInterface namespace

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/action/NewXmlServiceAction.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/action/NewYamlServiceAction.java

Since PhpStorm 2018.2 is the xml service creation broken. It cannot find the file. That makes me angry everytime when i need a services.xml
So here is the fix. It seems so that the /resources is not more needed anymore. I removed that, and he can find now the files.
I have also updated the Pipeline for PhpStorm 2018.3 release

Fix service.xml creating

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/extension/ServiceParameterCollector.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/extension/ServiceParameterCollectorParameter.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/stubs/ContainerCollectionResolver.java
src/main/resources/META-INF/plugin.xml

Other Plugins (in my case Shopware Plugin) can extend the parameters using the Extension Hookpoint.
The most code is copied from ServiceCollector extensionPoint
```php
public class DefaultServiceParameterCollector implements ServiceParameterCollector {
@Override
public void collectIds(@NotNull ServiceParameterCollectorParameter.Id parameter) {
parameter.add(new ContainerParameter("kernel.foo", "YAY", true));
}
}
```

Allow other plugins to extend container parameters

---

.gitmodules
src/main/resources/META-INF/plugin.xml

PhpStorm 2019.1 introduces `expectedArguments` and `expectedReturnValues` meta definitions to allow for approciate completion of constants and string values.
See official blog post here:
https://blog.jetbrains.com/phpstorm/2019/02/new-phpstorm-meta-php-features/
I went through Symfony framework/components and defined a lot of them here:
https://github.com/King2500/symfony-meta
People can fetch them via Composer now (as require-dev), but I think it would be better to have these bundled into this plugin.
Advantages:
* No need to require them in every Symfony project
* No need to have this requirement in composer.json (because it's a PhpStorm-specific thing and developers may not want to have this dependency there, when working with other developers/IDEs)
I added symfony-meta repo as …

Bundle .phpstorm.meta.php files for new expectedArguments completion

---

.gitmodules
src/main/resources/META-INF/plugin.xml

Similar to Symfony meta files I wrote them for Doctrine ORM and DBAL (and related stuff).
Since there is no dedicated Doctrine plugin atm and this plugin already has Doctrine completion stuff it made most sense for me to bundle meta files here as well.
This mainly adds completion for types, modes and hint constants in Query, Querybuilders, etc methods.
There is also a neat trick involved, when you write `$qb->where(` it suggests `$qb->expr()` thanks to PhpStorm's matching between `expectedReturnValues` and `expectedArguments` of methods. This makes writing QueryBuilder calls with complex expressions/conditions a lot easier :)
Some things like constant completion in array parameters are not yet possible because Jetbrains has to implement that first. (For example Types mapping for …

Bundle Doctrine meta files for expectedArguments/ReturnValues completion

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/util/dict/ServiceUtil.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/codeInspection/service/TaggedExtendsInterfaceClassInspectionTest.java

Context: Twig >= 1.38.0 or >= 2.7.0
Before:
- Twig_Extension aliased to Twig\Extension\AbstractExtension
After:
- Twig\Extension\AbstractExtension aliased to Twig_Extension
But we cannot just check for Twig\Extension\AbstractExtension instead of \Twig_Extension because users with old Twig version don't have this class.
So, we check with the interface \Twig_ExtensionInterface because it exists since 1.0.0 and 2.0.0 and works with >= 1.38.0 and >= 2.7.0 because \Twig\Extension\ExtensionInterface is aliased to  \Twig_ExtensionInterface

Services with tag twig.extension should implement Twig_ExtensionInterface

---

src/main/resources/META-INF/pluginIcon.svg
src/main/resources/META-INF/pluginIcon_dark.svg

This adds Symfony icons to plugin (supported by IDEA platform since 2019.1).
(see details here: https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_icon_file.html)
Icons will be shown in Settings > Plugins UI (see Screenshots below) and also in [Plugins Repository](https://plugins.jetbrains.com/).
When using light themes:
When using Darcula theme:

Add Symfony plugin SVG icons

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/installer/SymfonyInstallerUtil.java

I don't know if this is the case but `downloadFile` needs to follow redirect for this to work.

Fixed Symfony installer download to use https

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/util/PhpElementsUtil.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/form/FormOptionGotoCompletionRegistrarTest.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/form/fixtures/FormOptionGotoCompletionRegistrar.php

Using constants for options of form extensions is very common. This will add support of any type of constants to form options auto completion

added support for constants as FormOption

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/config/yaml/YamlCompletionContributor.java

Instead of `autowiring_type` it should be called `autowiring_types` 
see https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php#L60
Also `autowiring_types` is removed in Symfony 4.0, so I added this note in type text.
see https://github.com/symfony/symfony/pull/22773

Fixed typo/wrong YAML service attribute for autowiring_types

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/lang/ParameterLanguageInjector.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/lang/ParameterLanguageInjectorTest.java

Automatic injectors are not working correctly with heredocs and nowdocs. That causes issues like https://youtrack.jetbrains.com/issue/WI-47027 with enabled symfony plugin. The fix is provided

Fixed injection range for heredoc/nowdoc literals in automatic injectors

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/Settings.java

Fixes #1295 
By default, Symfony 4 generate application containers based on Kernel properties.
Method `Symfony\Component\HttpKernel\Kernel@initializeContainer()` use `Symfony\Component\HttpKernel\Kernel@getContainerClass()` to build file name for container based on following Kernel class properties:
- `$name` – base dir for Kernel class (src)
- `$class` – FQN for Kernel class, backslash replaced with underscore (App\Kernel > App_Kernel)
- `$environment` – configured environment, based on APP_ENV (Dev, Test, Prod, etc.)
- `$debug` – debug mode, adds **Debug** to file name, based on APP_DEBUG ("Debug" or empty string)
All these variables prepended to base name "Container".
So, default container filename for DEV environment with Debug enabled will always:
src + App_Kernel +Dev + Debug + …

added path for default container in Symfony 4

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/templating/util/TwigUtil.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/templating/util/TwigUtilTest.java

This was introduced in SensioFrameworkExtraBundle 4.0.
https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/CHANGELOG.md#40
Fixes #1082 #1296 #1138 
This is my first try to do something in Java, so I don't expect this PR to be pixel perfect yet. Please tell me how to improve, and I will :)

Support new snake_case templates

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/SettingsForm.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/profiler/ui/ProfilerSettingsDialog.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/ui/TwigNamespaceDialog.java

Fix browse folder buttons

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/ui/TwigSettingsForm.java

Instead of throwing an exception, handle `dumb mode` and explain it to the user.
Closes #1222

Twig settings are not available while indexing

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/config/SymfonyPhpReferenceContributor.java

Fixes not being able to follow template references with another extension than `*.twig` in `loadTemplate()` and `load()` calls with Twig version 1.38 and higher.

Added support for namespaced Twig classes

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/config/SymfonyPhpReferenceContributor.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/doctrine/EntityHelper.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/doctrine/ObjectManagerFindTypeProvider.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/doctrine/ObjectRepositoryResultTypeProvider.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/doctrine/ObjectRepositoryTypeProvider.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/doctrine/completion/DoctrineCompletionContributor.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/doctrine/intention/DoctrineRepositoryClassConstantIntention.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/doctrine/metadata/ObjectRepositoryFindGotoCompletionRegistrar.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/doctrine/metadata/util/DoctrineMetadataUtil.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/doctrine/querybuilder/QueryBuilderMethodReferenceParser.java

This PR is for #1401 where reasoning behind it is explained in more details

Attempt to use new persistance namespaces without breaking BC

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/translation/dict/TranslationUtil.java

In controller we get completion/reference as well as inspection support for `Translator(Interface)` methods `trans` and `transChoice`.
But if you use the PHP-template helper `$view['translator']` (which is `\Symfony\Bundle\FrameworkBundle\Templating\Helper\TranslatorHelper` with same method signatures) completion etc is not working:
```php
/** @var \Symfony\Component\Templating\PhpEngine $view */
$view['translator']->trans('<caret>' ...);
```
We have the following mapping in our `.phpstorm.meta.php`, so `$view['translator']` resolves to
`\Symfony\Bundle\FrameworkBundle\Templating\Helper\TranslatorHelper`:
```php
// $view['arg'] lookups
override(new \Symfony\Component\Templating\PhpEngine,
map([
// ...
'translator' => \Symfony\Bundle\FrameworkBundle\Templating\Helper\TranslatorHelper::class …
```

Added reference and inspection support for TranslatorHelper

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/config/php/PhpMessageSubscriberGotoCompletionRegistrar.java
src/main/resources/META-INF/plugin.xml
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/SymfonyLightCodeInsightFixtureTestCase.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/config/php/PhpMessageSubscriberGotoCompletionRegistrarTest.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/config/php/fixtures/classes.php

With this PR the autocompletion inside the [`MessageSubscriberInterface::getHandledMessage()`](https://github.com/symfony/symfony/blob/985f64b5af01ab2b54b054ebd8c527dca9fe8e6f/src/Symfony/Component/Messenger/Handler/MessageSubscriberInterface.php) method should work when typing the name of the method that will handle a certain event. The following cases are supported:
```php
public static function getHandledMessages(): iterable
{
yield FirstMessage::class => [
'method' => '<caret>',
];
yield 'FirstMessage' => [
'method' => '<caret>',
];
return [
FirstMessage::class => '<caret>',
'FirstMessage' => '<caret>',
];
}
```
I tried to restrict the autocompletion so that it works only for the cases described above to avoid suggestions in cases where nothing has to do with them. I'm also not sure …

Add support for autocompletion inside the MessageSubscriberInterface::getHandledMessages method

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/config/php/PhpConfigReferenceContributor.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/registrar/DicGotoCompletionRegistrar.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/util/PhpElementsUtil.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/util/PhpStringLiteralExpressionReference.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/config/php/PhpConfigReferenceContributorTest.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/config/php/fixtures/services.yml
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/dic/registrar/DicGotoCompletionRegistrarTest.java

See Symfony PRs:
- https://github.com/symfony/symfony/issues/37186
- https://github.com/symfony/symfony/pull/36778

support global Symfony DIC function: "service" and "param"

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/Settings.java

Unwanted behavior: the plugin tries to save its settings in the root directory and fails because of lacking permissions.
Without the leading slash the settings go to the projects `.idea` folder as wanted.

Remove leading slash from storage location (#1543)

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/config/yaml/YamlGoToDeclarationHandler.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/attribute/value/AttributeValueAbstract.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/attribute/value/AttributeValueInterface.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/attribute/value/DummyAttributeValue.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/attribute/value/XmlTagAttributeValue.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/attribute/value/YamlKeyValueAttributeValue.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/container/ImmutableDecoratorService.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/container/SerializableService.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/container/ServiceInterface.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/container/XmlService.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/container/util/ServiceContainerUtil.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/stubs/ServiceIndexUtil.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/stubs/indexes/ServicesDefinitionStubIndex.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/util/yaml/YamlHelper.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/dic/container/util/ServiceContainerUtilTest.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/dic/container/util/fixtures/services5.yml
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/stubs/indexes/ServicesDefinitionStubIndexTest.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/util/dict/ServiceUtilTempProjectTest.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/util/yaml/YamlHelperLightTest.java

support arrays for "resource" and "exclude" on autowrite which is use on Symfony >= 5 as default instead of global pattern

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/action/ui/SymfonyCreateService.form

PR removes hardcoded white background in Symfony Create Service Form output textarea field. Currently Symfony Create Service Form  with "Dracula" theme look like this:
After applying the patch:
and with "Intelij light" theme:

Removed hardcoded background in Symfony Create Service Form output textarea 

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/config/php/PhpConfigReferenceContributor.java

Static code analytics reports that `parameterList == null` condition is always `false` in the following statement
https://github.com/Haehnchen/idea-php-symfony2-plugin/blob/7fc5555f22dc3df7f1e34e8c4c7e59d54339c39e/src/main/java/fr/adrienbrault/idea/symfony2plugin/config/php/PhpConfigReferenceContributor.java#L164-L167
as the result of `psiElement.getContext()` is already tested against `null` in: 
https://github.com/Haehnchen/idea-php-symfony2-plugin/blob/80d33630d2dc9eaa959e64b8d914165046abf1b9/src/main/java/fr/adrienbrault/idea/symfony2plugin/config/php/PhpConfigReferenceContributor.java#L160-L162

Removed redundant null check in phpStringLiteralExpressionClassReference method

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/util/PhpElementsUtil.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/util/PhpElementsUtilTest.java

Error reported as #1599 could be reproduced by creating the following class hierarchy:
```php
class A extends B { public function foo() { /* .... */ }
class B extends A {  /* .... */ }
```
and then calling `PhpElementsUtil.getImplementedMethods(...)` for `foo` method.
Similar issue occurs in `de.espend.idea.php.toolbox.matcher.php.docTag.Php DocUtil.getImplementedMethods` but seperate PR is requried as this class is not part of this repository.
TODO:

Fixed #1599: Added protection against infinite recursion in PhpElementsUtil.getImplementedMethods

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/inspection/CaseSensitivityServiceInspection.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/util/yaml/YamlHelper.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/dic/inspection/CaseSensitivityServiceInspectionTest.java

Added additional check to fr.adrienbrault.idea.symfony2plugin.dic.inspection.CaseSensitivityServiceInspection if given YAML key text is not default env value. I wans't able to reproduce issue in other file formats. 
Open questions:
* Should `!YamlHelper.isDefaultEnvValue(keyText)` condition be evaluated only if `parameters` node is ancestor of keyText?

Fixed #1575: Inspection "Container sensitivity" is not expected to be emitted for default env values

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/container/util/ServiceContainerUtil.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/dic/container/util/ServiceContainerUtilTest.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/dic/container/util/fixtures/classes.php

Fixed https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/1640 by adding additional check if results of https://github.com/Haehnchen/idea-php-symfony2-plugin/blob/c8388e2429e6373db782c27bea15075cbec4a00b/src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/container/util/ServiceContainerUtil.java#L732 contains at least 2 elements before accessing them

Fixed #1640: Go to declaration throws ArrayIndexOutOfBoundsException on empty class const name

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/util/completion/PhpConstGotoCompletionProvider.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/completion/yaml/YamlGotoCompletionRegistrarTest.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/completion/yaml/fixtures/YamlGotoCompletionRegistrar.php

Skipp autocompletion for class consts. if cursor is placed before scope operator. This behaviour is consistent with class const. autocompletion in PHP code.

Fixed #1631: PhpConstGotoCompletionProvider throws IndexOutOfBoundsException when cursor is before scope operator

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/config/yaml/ConstantYamlReference.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/config/yaml/YamlReferenceContributor.java
src/main/resources/META-INF/plugin.xml
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/config/yaml/YamlReferenceContributorTest.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/config/yaml/fixtures/YamlReferenceContributor.php

Fixed #1667 by implementing PsiReferenceContributor. Patch demo: https://youtu.be/NkjXxbpb1Yc

Fixed #1667: Rename refactoring ignores constants inside yaml files 

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/profiler/utils/ProfilerUtil.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/profiler/ProfilerUtilTest.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/profiler/fixtures/profiler-index-with-route-prefix.html

1. Define prefix for profiler routes in Symfony application e.g,
```yaml
web_profiler_profiler:
resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
prefix: /prefix/_profiler
``` 
2. Configure plugin as described in #1674 
3. Open profiler menu 
Proposed patch ignores everything before `/_profiler/` segment (as is already part of the base url) when extracting profile URL from href attribute.

Fixed #1674: duplicated route prefix in profiler urls

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/ControllerMethodLineMarkerProvider.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/templating/TwigLineMarkerProvider.java

Replaced deprecated 
`LineMarkerInfo(PsiElement, TextRange, Icon, int, Function, GutterIconNavigationHandler<T>, GutterIconRenderer.Alignment)` 
constructor usages with
`LineMarkerInfo(PsiElement, TextRange, Icon, Function, GutterIconNavigationHandler, GutterIconRenderer.Alignment, Supplier)`
as javadoc suggest.

Fixed #1716: Deprecated LineMarkerInfo constructor usage

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/config/yaml/YamlCompletionContributor.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/completion/yaml/YamlCompletionContributorTest.java

Added missing
* `decoration_on_invalid` 
* `properties` 
* `configurator` 
* `bind` 
* `file` 
* `exclude`
keywords to suggestions under YAML service definition.
Ref. https://github.com/symfony/dependency-injection/blob/6b12d5bcd1e2f1cc9507cea6181787d642ec46b5/Loader/YamlFileLoader.php#L43-L108

Added missing services keywords to YamlCompletionContributor

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/routing/PhpLineMarkerProvider.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/routing/RouteHelper.java
src/main/resources/META-INF/plugin.xml
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/routing/PhpLineMarkerProviderTest.java

As mentioned in #1042 the plugin doesn't yet support php. This merge request adds a reference marker to the php controller in the php like so:
This is my first real Java application and plugin I contributed to. So feel free point out the rookie mistakes I made.

Adding a linemarker to php route config

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/config/xml/ConstantXmlReference.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/config/xml/ParameterXmlReference.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/config/xml/XmlReferenceContributor.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/config/yaml/YamlReferenceContributor.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/routing/RouteXmlReferenceContributor.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/config/xml/XmlReferenceContributorTest.java

```
java.lang.AssertionError: reference fr.adrienbrault.idea.symfony2plugin.config.xml.ParameterXmlReference(XmlText:null) was created for XmlToken:XML_DATA_CHARACTERS but target XmlText, provider fr.adrienbrault.idea.symfony2plugin.config.xml.XmlReferenceContributor$3@37527615
at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.assertReferenceUnderlyingElement(ReferenceProvidersRegistryImpl.java:191)
at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:165)
at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:141)
at …
```

#1574 #1834 fix all psi references which are not attached to itself

---

README.md
src/main/resources/META-INF/plugin.xml

Hi there, just wanted to buy a license for PHPStorm and had several small problems:
Leads to a 404 page. I then followed the linked mentioned below
and completed the, at least to me, unknown flow which ended in me creating a team account in addition to my personal account, which the license was assigned to. Had it reversed via support.
This PR corrects the link to the proper market place entry point that everyone should know. It also gives the correct flow to decide if you want a personal license or a organization one.
I'm not sure which of the files is responsible for the view inside the plugin overview, so I corrected all links I could find.

Fixed bad links to jetbrains plugin marketplace

---

gradle.properties
src/main/java/fr/adrienbrault/idea/symfony2plugin/stubs/indexes/visitor/AnnotationRouteElementWalkingVisitor.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/templating/util/TwigUtil.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/util/PhpPsiAttributesUtil.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/SymfonyLightCodeInsightFixtureTestCase.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/action/naming/JavascriptServiceNameStrategyTest.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/templating/util/TwigUtilTest.java

--------------------
**options 1**
```
- com.jetbrains.php.config.library.PhpRuntimeLibraryRootsProvider#getAdditionalProjectRootsToIndex
- if (ApplicationManager.getApplication().isUnitTestMode() && !hasWebModules(project)) {
ContainerUtil.or(ModuleManager.getInstance(project).getModules(), ModuleTypeWithWebFeatures::isAvailable)
```
**option 2**
its just a log error; find a suitable way to disable that log errors let fail tests
------------
```
`com.jetbrains.php.config.library.PhpLibraryRoot.MyPhpLibraryRootProvider#getLibraryRoots`
```
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:200)
at com.jetbrains.php.config.library.PhpLibraryRoot$MyPhpLibraryRootProvider.getLibraryRoots(PhpLibraryRoot.java:104)
at com.jetbrains.php.config.library.PhpRuntimeLibraryRootsProvider.lambd …

2022.2 ci build infrastructure

---

build.gradle.kts
src/main/resources/META-INF/plugin.xml
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/completion/IncompletePropertyServiceInjectionContributorTest.java

https://github.com/JetBrains/gradle-intellij-plugin/issues/1094 via upgrading
"org.jetbrains.intellij" to "1.10.0"

fix: "Template not found: PHP Getter Method"

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/doctrine/DoctrineUtil.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/doctrine/EntityHelper.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/stubs/indexes/PhpTwigTemplateUsageStubIndex.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/templating/util/PhpMethodVariableResolveUtil.java

Hi, PhpStorm here! We're working on improving indexing performance and saw an optimization opportunity. It's generally recommended to avoid using recursive visitors, since they traverse whole trees which might be very deep. In case of Symfony Plugin we can replace them with other techniques like traversing only needed elements and/or ControlFlow (which is a linear data structure and contains less nodes than trees)
This change results into at least 10% indexing speed up on our internal tests.

Speed up indexing: replace recursive visitors with linear scans

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/command/SymfonyCommandRunConfiguration.java

In windows bin/console is not executable, so trying tu run command (by clicking green play button near class name) fails.
Also changed opened terminal to be writable, since it was useless for interactive commands.

Set php as executable on run command

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/inspection/MissingServiceInspection.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/routing/inspection/PhpRouteMissingInspection.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/templating/PhpTemplateMissingInspection.java

Instead of using static signature lists to check if the route, service, and template "missing" inspections apply, we can instead check if the element's `PsiReference` list contains the relevant reference type. This change allows these inspections to operate in the same contexts as auto-completion, such as when the reference was tagged with a PhpDoc hash (e.g., `#Route`) or configured through the settings panel.
Thanks!
Fixes #2255

Use PsiReference list to determine if "missing" inspections apply

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/assetMapper/AssetMapperUtil.java

Allow AssetMapper to resolve scoped npm packages (e.g. @hotwired/turbo)

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/codeInsight/SymfonyImplicitUsageProvider.java
src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/codeInsight/SymfonyImplicitUsageProviderTest.java

Currently `#[AsEventListener]` only marks methods as implicitly used when the attribute is placed on the class and has an explicit `method` argument. But in my experience that's not the most common usage of the attribute and both the [documentation](https://symfony.com/doc/current/event_dispatcher.html#defining-event-listeners-with-php-attributes) and unit tests ([1](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/EventDispatcher/Tests/Fixtures/TaggedMultiListener.php), [2](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/EventDispatcher/Tests/Fixtures/TaggedInvokableListener.php)) show multiple possibilities, which are:
1. `#[AsEventListener]` on the method itself (I believe the most common)
2. `#[AsEventListener]` on the class with an explicit `method` …

Enhance AsEventListener support

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/translation/ConstraintMessageGotoCompletionRegistrar.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/translation/annotation/ConstraintMessageAnnotationReferences.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/translation/dict/TranslationUtil.java

Hi @Haehnchen
The plugin only provide autocompletion for Constraint properties which starts with "message" but it's more common to see the suffix "message".
For instance https://symfony.com/doc/current/reference/constraints/Length.html
has `minMessage` and `maxMessage` property.
I tried to make the change, but I'm not familiar to JAVA, so open to any comment :) 
Thanks a lot for your time and this project.

Add support for suffix "message" in Constraint properties

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/webDeployment/ServiceContainerRemoteFileStorage.java

The class was kept for compatibility and is going to be removed from the platform soon.
FTR, I didn't try to compile the resulting code (the change is pretty trivial and shouldn't cause any problem).

Dropping usages of deprecated `org.apache.sanselan.util.IOUtils` class

---

src/main/java/fr/adrienbrault/idea/symfony2plugin/SettingsForm.form
src/main/java/fr/adrienbrault/idea/symfony2plugin/SettingsForm.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/Symfony2ProjectComponent.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/ui/MethodParameterReferenceSettingsForm.java
src/main/java/fr/adrienbrault/idea/symfony2plugin/ui/MethodSignatureTypeSettingsForm.java

The `help` button in `Settings > PHP > Symfony > Method References` is targeting `https://espend.de/phpstorm/plugin/symfonyextension/method_parameter.html`
The `help` button in `Settings > PHP > Symfony > Type Provider` is targeting `https://espend.de/phpstorm/plugin/symfonyextension/signature_type.html`
And both url are 404 Not found.
In this MR we replace url by those targeting PHPStorm documentation (the new documentation) https://www.jetbrains.com/help/phpstorm/symfony-support.html
As `HELP_URL` is only used on settings main page I remove the constant to replace it by a string. (Tell me if it's good for you)
I also change the `buttonHelp` label by `Project Page / Documentation` as it's not the Help page anymore. But the project Page and this project page contains documentation like. …

fix: help buttons targeting a not found page
