- META-INF/plugin.xml
> Fix small typo in Symfony2GroupService action group

- tests/fr/adrienbrault/idea/symfony2plugin/tests/SymfonyLightCodeInsightFixtureTestCase.java
see also `assertCompletionContains(filename ...)`
> Fix parameter name for assertCompletionNotContains

- CHANGELOG.md
> Fixed small typo in changelog

- src/main/java/fr/adrienbrault/idea/symfony2plugin/routing/PhpRouteReferenceContributor.java
- src/main/java/fr/adrienbrault/idea/symfony2plugin/templating/util/TwigTypeResolveUtil.java
- src/main/java/fr/adrienbrault/idea/symfony2plugin/util/IdeHelper.java
- src/main/java/fr/adrienbrault/idea/symfony2plugin/util/dict/ServiceUtil.java
> When able to, detect Symfony 4 "public" directory

- src/main/java/fr/adrienbrault/idea/symfony2plugin/action/bundle/NewBundleCommandAction.java
- src/main/java/fr/adrienbrault/idea/symfony2plugin/util/psi/PhpBundleFileFactory.java
> Adjust resource path for bundle file creation

- src/main/java/fr/adrienbrault/idea/symfony2plugin/installer/SymfonyInstallerUtil.java
> Fixed Symfony installer version selection to use https

- src/main/java/fr/adrienbrault/idea/symfony2plugin/form/util/FormOptionsUtil.java
- src/main/java/fr/adrienbrault/idea/symfony2plugin/form/util/FormUtil.java
- src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/form/util/FormUtilTest.java
see symfony/symfony#24530 for details
> Symfony 4.2: Support improved form type extensions #1246

- src/main/java/fr/adrienbrault/idea/symfony2plugin/completion/xml/XmlGotoCompletionRegistrar.java
> Add class name autocompletion to new service definition

- .gitmodules
see changes https://github.com/King2500/symfony-phpstorm-meta/compare/230bfd45a46882ee8fe1f5831cb904458ed32dbe...e4d14c1504b0f7f5194bed3f23e8db37f56d350a
And I renamed my repo to symfony-phpstorm-meta.
> Updated symfony-phpstorm-meta files

- src/main/java/fr/adrienbrault/idea/symfony2plugin/action/generator/naming/DefaultServiceNameStrategy.java
- src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/action/naming/DefaultServiceNameStrategyTest.java
> Fix service generation when a class name contains "Bundle"and is not in a Bundle

- src/main/java/fr/adrienbrault/idea/symfony2plugin/stubs/indexes/ContainerBuilderStubIndex.java
Let's assume some code fragment with a deep method references chain. There will be S.O.E. by this indexer as it recursively traverses the tree at the custom depth
> Container stub index performance: move to unrecursive indexer

- src/main/java/fr/adrienbrault/idea/symfony2plugin/stubs/indexes/ContainerBuilderStubIndex.java
Fix [issue](https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/1339) by deleting access to another index in the indexing process
> Issue 1339

- src/main/java/fr/adrienbrault/idea/symfony2plugin/ui/ContainerSettingsForm.java
- src/main/java/fr/adrienbrault/idea/symfony2plugin/ui/RoutingSettingsForm.java
Please merge this pr with new place of icon available since 19.2
> WebDeploymentIcons.Download will be removed soon

- src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/attribute/value/PhpKeyValueAttributeValue.java
- src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/container/util/ServiceContainerUtil.java
- src/main/java/fr/adrienbrault/idea/symfony2plugin/stubs/indexes/ServicesDefinitionStubIndex.java
- src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/dic/container/util/ServiceContainerUtilTest.java
- src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/dic/container/util/fixtures/services.php
- src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/stubs/indexes/ServicesDefinitionStubIndexTest.java
- src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/stubs/indexes/fixtures/services.php
Extracted by common implementation based on: https://github.com/symfony/symfony/issues/37186
> index service definition for PHP files

- src/main/java/fr/adrienbrault/idea/symfony2plugin/util/completion/PhpConstGotoCompletionProvider.java
- src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/completion/yaml/YamlGotoCompletionRegistrarTest.java
- src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/completion/yaml/fixtures/YamlGotoCompletionRegistrar.php
In the following scenario
```yaml
services:
App\Service\BarService:
arguments:
- !php/const App\Service\FooService::<caret>
```
consts with private and protected modifier shouldn't be suggested in autocompletion as they are not accessible by container.
<details>
<summary>Example stacktrace (obfuscated)</summary>
```
In FileLoader.php line 173:
[Symfony\Component\Config\Exception\LoaderLoadException]                                                                                                                                                   
The file "<project>/src/../config/services.yaml" does not contain valid YAML: The constant "App\Service\FooService::PRIVATE_CONST" is not defined at line 77 (ne  
ar "!php/const App\Service\FooService::PRIVATE_CONST") in …
```
> Excluded non-public consts from !php/const autocompletion 

- src/main/java/fr/adrienbrault/idea/symfony2plugin/config/ConfigLineMarkerProvider.java
- src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/config/ConfigLineMarkerProviderTest.java
@see https://symfony.com/blog/new-in-symfony-5-3-configure-multiple-environments-in-a-single-file
> support navigation for "Symfony 5.3: Configure Multiple Environments in a Single File"

- src/main/java/fr/adrienbrault/idea/symfony2plugin/library/DoctrineMetaLibraryRootProvider.java
- src/main/java/fr/adrienbrault/idea/symfony2plugin/library/PluginLibraryRootProvider.java
- src/main/java/fr/adrienbrault/idea/symfony2plugin/library/SymfonyMetaLibraryRootProvider.java
- src/main/resources/META-INF/plugin.xml
> King2500 feature/library provider

- src/main/java/fr/adrienbrault/idea/symfony2plugin/templating/inspection/TemplateCreateByNameLocalQuickFix.java
- src/main/java/fr/adrienbrault/idea/symfony2plugin/templating/inspection/TemplateExistsAnnotationPhpAttributeLocalInspection.java
- apply similar template guest only if annotation provides template
- provide camlized template value as fallback
> underscore should be the preferred template creation quickfix

- src/main/java/fr/adrienbrault/idea/symfony2plugin/completion/IncompletePropertyServiceInjectionContributor.java
- src/main/java/fr/adrienbrault/idea/symfony2plugin/dic/intention/PhpPropertyArgumentIntention.java
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/PhpPropertyArgumentIntention/description.html
- src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/completion/IncompletePropertyServiceInjectionContributorTest.java
- src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/completion/fixtures/IncompletePropertyServiceInjectionContributor.php
> add quickfix for missing property: try to find a valid service injection and autowire it

- .github/workflows/gradle.yml
- build.gradle.kts
- gradle.properties
- src/main/java/fr/adrienbrault/idea/symfony2plugin/doctrine/dict/DoctrineModelFieldLookupElement.java
- src/main/java/fr/adrienbrault/idea/symfony2plugin/doctrine/querybuilder/QueryBuilderCompletionContributor.java
- src/main/java/fr/adrienbrault/idea/symfony2plugin/external/toolbox/provider/ControllerToolboxProvider.java
- src/main/java/fr/adrienbrault/idea/symfony2plugin/profiler/Symfony2WebProfilerForm.java
- src/main/java/fr/adrienbrault/idea/symfony2plugin/profiler/widget/SymfonyProfilerWidget.java
- src/main/java/fr/adrienbrault/idea/symfony2plugin/templating/util/TwigExtensionParser.java
- src/main/java/fr/adrienbrault/idea/symfony2plugin/util/controller/ControllerActionLookupElement.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/SymfonyLightCodeInsightFixtureTestCase.java
- src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/action/naming/JavascriptServiceNameStrategyTest.java
- src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/intentions/yaml/dic/YamlCreateServiceArgumentsCallbackTest.java
- src/test/java/fr/adrienbrault/idea/symfony2plugin/tests/intentions/yaml/dic/YamlUpdateArgumentServicesCallbackTest.java
> infrastructure for 2022.3.2

- src/main/java/fr/adrienbrault/idea/symfony2plugin/routing/RouteHelper.java
> add canonical routes to index

- src/main/java/fr/adrienbrault/idea/symfony2plugin/security/VoterGotoCompletionRegistrar.java
Fix issue: https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/2413
> fix voter goto completion for Symfony 4/5/6
